services:
  taskd:
    image: johnivore/taskd:latest
    container_name: "taskd"
    restart: "unless-stopped"
    volumes:
      - "/srv/taskd:/var/taskd"
    ports:
      - "53589:53589"
    environment:
      # used during certificate generation
      - "EXPIRATION_DAYS=10000"               # default: 365
      - "ORGANIZATION=My awesome company"     # default: ""
      - "CN=sync.example.com"                 # default: localhost.localdomain
      - "COUNTRY=Netherlands"                 # default: ""
      - "STATE=Amsterdam"                     # default: ""
      - "LOCALITY="                           # default: ""
